### ISSUE TITLE
Evidence and Pictures are Not in the Report

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [GhostManager/Ghostwriter#74] opened 2020-05-20 23:16 UTC
Hi,

Thank you for making this tool. I am impressed. 

However, I have an issue. None of the reports that I generate seem to automatically add the picture evidence to the report. I don't doubt that this is a self-inflicted issue. I just don't fully understand how to resolve it. I read the wiki. But, I'm missing something somewhere. Are there any walkthroughs that aren't on the wiki that I can look at?

**Comment by chrismaddalena** [comment] 2020-05-21 06:46
It depends on the type of report. PowerPoint and Word reports will include evidence files. Evidence files will be inserted only where you add the placeholder text for the associated image or text file. While editing a finding, look at the Keyword Reference & Instructions section at the top of the page for more information.

if you are editing a finding, you can click the Upload Evidence button to attach a file. Once uploaded, the placeholder is automatically inserted.

You can also type `@` to engage autocomplete. As you begin to type `{{` you will see a list of available placeholders for that finding.

Allowed image extensions: png, jpeg, and jpg
Allowed text extensions: txt, ps1, py, md, and log

If the file extension is supported, Ghostwriter will replace the placeholder text with the evidence file.

If evidence is not appearing, the placeholder may be missing, does not match the "friendly name" of an attached file, or may reference an unsupported file type.

In a PowerPoint deck, only evidence in the Description field will be included.

**Comment by g3ksmithington** [comment] 2020-07-22 15:29
I'm going to echo OP here. I got the latest Ghostwriter up and running 3 weeks ago and I'm having a difficult time with evidence embedding in the draft report while writing a report. If I follow the WISYWIG editor to upload and insert evidence only the first evidence file is displayed in the draft report. It's not a huge deal as I can manually add in that evidence when we generate the final report, but it would be nice to figure out how to make sure that feature works in the future.  

Here is how it's formatted in the finding:
![image](https://user-images.githubusercontent.com/854881/88194895-f88ac180-cc04-11ea-8eab-7163b8c81357.png)

There are some extra returns at the end of the image in the report, but other screenshots besides the first one (had to censor the data):
![image](https://user-images.githubusercontent.com/854881/88195349-91214180-cc05-11ea-9426-2adb646d0a27.png)

Additionally, if I add evidence from the Attached Findings page and manually add the placeholder into the WISYWIG, it doesn't appear in the draft report.

**Comment by chrismaddalena** [comment] 2020-08-24 17:50
Quick update: we've been making changes to these functions for an upcoming release, so I did some testing with a bunch of image files. I successfully inserted several images in series and they all appeared in the report. I am using a modified code base, but we have not changed anything that should impact evidence uploading or rendering.

There was an issue with some "friendly names" that led to evidence files being skipped. We fixed that in the 15 June 2020 release, but you might not have that. The issue involved evidence files names with periods. The reporting engine strips the `{{.` from the lines to get the name. The old code removed each character individually with `replace()`, so it would replace `.` with nothing and end up skipping evidence with periods in the name.

If the missing files have names like `something.log`, try removing the period. The solution is updating, but that would work around the issue until you can update.

**Comment by BetaMaxHeadroom** [comment] 2020-10-02 16:21
I don't know if this could ever be an option. But, if evidence can be added in a similar way that PwnDoc (https://github.com/pwndoc/pwndoc) implements it, that would be really helpful. Some pictures work for me. But, I'm not exactly certain why some do not.

**Comment by chrismaddalena** [comment] 2020-11-20 19:07
@BetaMaxHeadroom Could you explain? Ghostwriter adds images as inline shapes, which is how Word handles images.

**Comment by andrewchiles** [comment] 2021-02-11 15:50
**Update**: We recently found an issue where supported image extension comparisons were **case sensitive** and thus if you had an image with a `PNG` extension it wouldn't end up in the report because the comparison was looking for `png`, `jpg`, `jpeg`, etc. It wasn't lowercasing all extensions before the comparison. This will be fixed in Master when the next GW release is pushed to GitHub. Current estimate is end of Q1 2021

**Comment by chrismaddalena** [comment] 2021-03-04 06:07
The above-mentioned issue is resolved with the latest release: https://github.com/GhostManager/Ghostwriter/releases/tag/v2.1

**Closed by chrismaddalena** 2021-03-04 06:07 UTC

**Comment by gmcblg** [comment] 2022-10-06 16:01
> **Update**: We recently found an issue where supported image extension comparisons were **case sensitive** and thus if you had an image with a `PNG` extension it wouldn't end up in the report because the comparison was looking for `png`, `jpg`, `jpeg`, etc. It wasn't lowercasing all extensions before the comparison. This will be fixed in Master when the next GW release is pushed to GitHub. Current estimate is end of Q1 2021

Not sure if there's been a regression re: file extension case sensitivity since the v2.1 release, but this behaviour (capitalised `PNG`/`JPG` extensions rendering in evidence import but not being exported to the final `docx`) was reproducible on Ghostwriter v3.0.5. For context, was using Windows' Snipping Tool > save image > defaults to capital extensions.

**Comment by chrismaddalena** [comment] 2022-10-10 22:17
@gmcblg I'm not sure what happened. It looks like the change I made to address that never merged with that release and it went unnoticed for over a year. The Windows Snipping tool is the only tool I've seen that routinely saves files with all uppercase extensions, so there might be a lower chance of someone encountering the issue and reporting it.

I'm including a fix with a minor release today. Thanks for letting me know about it.
