### ISSUE TITLE
Inverted severity weight in newly deployed instance

### ISSUE THREAD

**Issue by fastlorenzo** [GhostManager/Ghostwriter#292] opened 2023-02-20 22:51 UTC
**Describe the bug**

The severity weight within a newly deployed GW instance is sorted from 1 (informational) to 5 (critical). 

However, the documentation states that the lower severity should be more severe:

![image](https://user-images.githubusercontent.com/768639/220208291-7b2c5166-3568-411a-bde8-d6412131df29.png)

I've checked the initial data and this looks correct, not sure how this happens: https://github.com/GhostManager/Ghostwriter/blob/9cd4789651e4b89bab651d6fcdc896a137bb1656/ghostwriter/reporting/fixtures/initial.json#L1-L45

Given that this matches the `pk` field in the initial data, it might be related to it (but this is just a guess).

**To Reproduce**
1. Install a new instance of Ghostwriter
2. Check the severity in the admin panel

**Expected Behavior**

Severity should be weighted from 1 (critical) to 5 (informational), to match the data in https://github.com/GhostManager/Ghostwriter/blob/9cd4789651e4b89bab651d6fcdc896a137bb1656/ghostwriter/reporting/fixtures/initial.json.

**Screenshots**

![image](https://user-images.githubusercontent.com/768639/220208102-e5f86501-ebab-4c82-8e5f-21944db6bac7.png)

**Server Specs:**
 - Ghostwriter: 3.2.2

**Additional context**

N/A

**Comment by chrismaddalena** [comment] 2023-02-21 22:13
Thanks for letting me know, @fastlorenzo. It's likely related to the changes in v3.2 for customizing severity categories. Ghostwriter now adjusts weights like positions for findings. The initial values are loaded from Informational -> Critical. When the weight for Info is set to `5`, it gets adjusted to `1` because it's the only severity category in the database. Then Low's weight is changed from 4 to 2, and so on. The weights end up reversed.

Reversing the order in which the initial severity categories are loaded should resolve this.

**Comment by fastlorenzo** [comment] 2023-02-22 02:44
This explains why the values were changing automatically for the other severity when I was fixing it from the admin panel 😅
Thanks for the quick fix @chrismaddalena!

**Comment by chrismaddalena** [comment] 2023-02-22 17:56
Sure thing. Thanks for reporting it! I missed this in testing. v3.2 included changes to allow you to change severity category names, replace them, or add new categories. Some templates still check `weight` values from 1-5 to apply some styling, so there needed to be a mechanism to close gaps introduced by edits.

Once I looked into it, I confirmed the problem was loading the categories from `Low` to `Critical`. All the `weight` values were reversed by the mechanism mentioned above. It'll be fixed in the next release.

**Closed** 2023-03-22 22:50 UTC
Labels: bug
