### ISSUE TITLE
Make Client Findable Using Shortname

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#294] opened 2023-03-14 10:27 UTC
My colleagues are used to referring to client by their short name already (e.g., "BWB" instead of "Big Whoop Bank"). Ghostwriter already allows **defining** such short name for a client. However, when using the "Search Clients..." feature in the menu bar, the **search** seems to only consider the full client name. 

**Describe the solution you'd like**
I'd like the "Search Clients.." functionality to also consider the client.shortname field, so I can quickly find clients using their a short name.

**Describe alternatives you've considered**
Haven't found one yet. Since the shortname is not listed in the list of clients, displaying all clients and then using the browsers search functionality to find the shortname does not work either.

**Additional context**
Running v3.2.2, released 13 February 2023

**Comment by chrismaddalena** [comment] 2023-03-15 21:21
Good call, @er4z0r! I modified the client filter to search for partial hits against the name, short name, and code name in one field. That makes it simpler and checks all the possible fields.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/10526228/225445924-dd81ff1d-3aa4-4cc3-80d4-db124061efa7.png">

I also applied this to the project list filter. While looking at that filter, I noticed there was no way to filter by project type, so I added that as an option.

<img width="1778" alt="image" src="https://user-images.githubusercontent.com/10526228/225446416-bd70996f-a546-48df-8c78-acee326a4af5.png">

**Comment by er4z0r** [comment] 2023-04-21 15:17
Thank you for the update that came with v.3.2.3 while it does indeed allow search for the client using their short name. It does not fully address my original issue. 

My goal was to speed up the workflow as much as possible, so **instead of navigating to the Clients page**,  I was especially hoping for the "Search Clients ..." field in the pull-out menu on the left to use both the full name and shortname when searching. 

Currently (on 3.2.6) that "Search Clients ..."  field will search for clients using their full company name.

I know: It is just 1-2 clicks extra, but if you're doing it a lot, it adds up. For me (without CRM integration) I end up adding the projects manually and thus having to look up a client quiet often.

**Comment by chrismaddalena** [comment] 2023-04-21 18:50
@er4z0r Thanks for explaining. The client search in the sidebar should work with partial or complete names and short names. That was the intention of the update, but I overlooked something. The other search bars submit the search to the filter, while the client search searches differently and filters by full name.

**Comment by chrismaddalena** [comment] 2023-04-21 21:17
This will be fixed in the next patch. The sidebar's search field needed an updated `name` attribute to use the new filter changes properly. You can see a sidebar search for "so" returns two results here. The search term is also correctly inserted into the relevant field, as was intended.

* SpecterOps because the short name is SO
* Test 2 because the codename is WIRELESS SOUFFLE

![image](https://user-images.githubusercontent.com/10526228/233736028-b2f2cb3a-4453-472b-94f3-b54ebbc19c31.png)

**Closed** 2023-05-01 18:05 UTC
